
package dk.mhr.ihc.wsdl.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-12T18:01:53.033+01:00
 * Generated source version: 3.1.5
 * 
 */
public final class OpenAPIService_OpenAPIServiceBindingPort_Client {

    private static final QName SERVICE_NAME = new QName("utcs", "OpenAPIServiceService");

    private OpenAPIService_OpenAPIServiceBindingPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OpenAPIServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OpenAPIServiceService ss = new OpenAPIServiceService(wsdlURL, SERVICE_NAME);
        OpenAPIService port = ss.getOpenAPIServiceBindingPort();  
        
        {
        System.out.println("Invoking getProjectInfo...");
        dk.mhr.ihc.wsdl.cxf.WSProjectInfo _getProjectInfo__return = port.getProjectInfo();
        System.out.println("getProjectInfo.result=" + _getProjectInfo__return);


        }
        {
        System.out.println("Invoking disableSubscription...");
        dk.mhr.ihc.wsdl.cxf.ArrayOfint _disableSubscription_parameter3 = null;
        port.disableSubscription(_disableSubscription_parameter3);


        }
        {
        System.out.println("Invoking enableSubscription...");
        dk.mhr.ihc.wsdl.cxf.ArrayOfint _enableSubscription_parameter2 = null;
        port.enableSubscription(_enableSubscription_parameter2);


        }
        {
        System.out.println("Invoking getDatalineInputIDs...");
        dk.mhr.ihc.wsdl.cxf.ArrayOfWSDatalineResource _getDatalineInputIDs__return = port.getDatalineInputIDs();
        System.out.println("getDatalineInputIDs.result=" + _getDatalineInputIDs__return);


        }
        {
        System.out.println("Invoking waitForEvents...");
        int _waitForEvents_parameter1 = 0;
        dk.mhr.ihc.wsdl.cxf.WSEventPackage _waitForEvents__return = port.waitForEvents(_waitForEvents_parameter1);
        System.out.println("waitForEvents.result=" + _waitForEvents__return);


        }
        {
        System.out.println("Invoking setValues...");
        dk.mhr.ihc.wsdl.cxf.ArrayOfWSResourceValueEvent _setValues_parameter7 = null;
        boolean _setValues__return = port.setValues(_setValues_parameter7);
        System.out.println("setValues.result=" + _setValues__return);


        }
        {
        System.out.println("Invoking getFWVersion...");
        dk.mhr.ihc.wsdl.cxf.WSVersionInfo _getFWVersion__return = port.getFWVersion();
        System.out.println("getFWVersion.result=" + _getFWVersion__return);


        }
        {
        System.out.println("Invoking getDatalineOutputIDs...");
        dk.mhr.ihc.wsdl.cxf.ArrayOfWSDatalineResource _getDatalineOutputIDs__return = port.getDatalineOutputIDs();
        System.out.println("getDatalineOutputIDs.result=" + _getDatalineOutputIDs__return);


        }
        {
        System.out.println("Invoking getAPIVersion...");
        int _getAPIVersion__return = port.getAPIVersion();
        System.out.println("getAPIVersion.result=" + _getAPIVersion__return);


        }
        {
        System.out.println("Invoking getUptime...");
        long _getUptime__return = port.getUptime();
        System.out.println("getUptime.result=" + _getUptime__return);


        }
        {
        System.out.println("Invoking authenticate...");
        java.lang.String _authenticate_parameter5 = "";
        java.lang.String _authenticate_parameter6 = "";
        boolean _authenticate__return = port.authenticate(_authenticate_parameter5, _authenticate_parameter6);
        System.out.println("authenticate.result=" + _authenticate__return);


        }
        {
        System.out.println("Invoking getValues...");
        dk.mhr.ihc.wsdl.cxf.ArrayOfint _getValues_parameter4 = null;
        dk.mhr.ihc.wsdl.cxf.ArrayOfWSResourceValue _getValues__return = port.getValues(_getValues_parameter4);
        System.out.println("getValues.result=" + _getValues__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking getTime...");
        dk.mhr.ihc.wsdl.cxf.WSDate _getTime__return = port.getTime();
        System.out.println("getTime.result=" + _getTime__return);


        }

        System.exit(0);
    }

}
